spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JDBC driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT token ???? (??? ???? ???? ??)
spring.jwt.refresh-token-validity-in-seconds=1209600
spring.jwt.access-token-validity-in-seconds=604800

# H2 ??
spring.h2.console.settings.web-allow-others=true

# OAuth2 scope & redirect URI (? ??? ?? ??)
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://wooms.duckdns.org/api/login/oauth2/code/google

# Mail ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS S3 URL ? ??
cloud.aws.s3.url=https://dowooms.s3.ap-northeast-2.amazonaws.com/
cloud.aws.region.static=ap-northeast-2
cloud.aws.region.auto=false
cloud.aws.stack.auto=false

# OpenAI Audio API endpoint
spring.ai.openai.audio.speech.base-url=https://api.openai.com/v1/audio/speech

# prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
